#!/bin/bash

BIN_AWK=${0}.awk

command kubectl get secret -o json "$@" | jq 'select(.type="kubernetes.io/tls") | .data | [."tls.key", ."tls.crt", ."ca.crt"//""] | .[] | @base64d' -r | gawk -f $BIN_AWK
