#!/bin/bash

reset="$(tput sgr0)"
bold="$(tput bold)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
gray="$(tput setaf 8)"
magenta="$(tput setaf 13)"

declare -A color_map=()

color_map[ContainerCreating]="$magenta"
color_map[Pending]="$yellow"
color_map[Running]="$green"
color_map[Error]="$red"
color_map["[a-zA-Z0-9]\+BackOf[a-zA-Z0-9]\+"]="$red"
color_map[Terminating]="$gray"
color_map[Finished]="$gray"
color_map[Completed]="$gray"
color_map[NotReady]="$red"
color_map[Ready]="$green"
color_map[SchedulingDisabled]="$yellow"

regex=""
for word in ${!color_map[@]}; do
  regex+="s|$word|${color_map[$word]}&$reset|g; "
done

regex+='
s|\b\([0-9]\+\)/\1\b|'$green'&'$reset'|g;
s|\b0/[1-9]\+\b|'$red'&'$reset'|g;
s|\b[1-9][1-9]*/[0-9]\+\b|'$yellow'&'$reset'|g;
'

if ${KC_DEBUG:-false}; then
  echo "regex: $regex"
  exec sed ${KC_TRACE:+--debug} -e "$regex"
fi

kubectl "$@" | sed -e "$regex"
